const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),net=require('node:net'),{spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..'),dataRoot=path.join(root,'tmp','next-test-'+crypto.randomUUID());let child,base,created,cookie,csrf;
before(async()=>{
 fs.mkdirSync(dataRoot,{recursive:true});
 fs.copyFileSync(path.join(root,'backend/data/editorial-demo.json'),path.join(dataRoot,'editorial-demo.json'));
 fs.writeFileSync(path.join(dataRoot,'editorial-requests.json'),'[]');
 process.env.V1_DATA_DIR=dataRoot;const sql=require('../cms/db');require('../cms/migrate').migrate();sql.run('INSERT INTO users VALUES(?,?,?,?,?,?)','next-qa','next-qa@example.org','QA Next',await require('../cms/security').passwordHash('Next-admin-test-only'),'admin',new Date().toISOString());sql.db.close();
 const probe=net.createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));base='http://127.0.0.1:'+port;
 child=spawn(process.execPath,[require.resolve('next/dist/bin/next'),'start','-p',String(port),'-H','127.0.0.1'],{cwd:root,env:{...process.env,NODE_ENV:'production',NEXT_TELEMETRY_DISABLED:'1',V1_DATA_DIR:dataRoot},stdio:['ignore','pipe','pipe'],windowsHide:true});
 const log=[];child.stdout.on('data',b=>log.push(b.toString()));child.stderr.on('data',b=>log.push(b.toString()));
 for(let i=0;i<100;i++){try{if((await fetch(base+'/api/demo/articles')).ok){const login=await fetch(base+'/admin/login',{method:'POST',redirect:'manual',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'next-qa@example.org',password:'Next-admin-test-only'})});cookie=login.headers.get('set-cookie').split(';')[0];const html=await(await fetch(base+'/admin',{headers:{Cookie:cookie}})).text();csrf=html.match(/name="csrf-token" content="([^"]+)"/)[1];return;}}catch{}await new Promise(r=>setTimeout(r,200));}throw Error(log.join(''));
});
after(async()=>{if(child){child.kill();await new Promise(resolve=>{child.once('exit',resolve);setTimeout(resolve,3000).unref();});}});
async function request(url,method='GET',body){return fetch(base+url,{method,headers:{Cookie:cookie,'X-CSRF-Token':csrf,...(body?{'Content-Type':'application/json',Origin:base}:{})},body:body?JSON.stringify(body):undefined,redirect:'manual'});}
test('HTML delle pagine identico al documento magazine originale',async()=>{const expected=fs.readFileSync(path.join(root,'public/demo.html'),'utf8');for(const url of ['/','/notizie','/notizie/prova','/aniem','/servizi','/servizi/lavoro','/chi-siamo','/convenzioni','/associarsi','/contatti','/analisi']){const r=await request(url);assert.equal(r.status,200,url);assert.equal(await r.text(),expected,url);}});
test('Asset serviti senza alterazioni e query studio conservata',async()=>{for(const name of ['js/magazine.js','css/magazine.css','css/demo-refinements.css','assets/docs/Scheda-adesione-CONFAPI-ROMA.pdf']){const r=await request('/'+name);assert.equal(r.status,200);assert.deepEqual(Buffer.from(await r.arrayBuffer()),fs.readFileSync(path.join(root,'public',name)));}const actual=await(await request('/api/demo/articles?studio=1')).json();assert.deepEqual(actual.map(a=>a.id).sort(),JSON.parse(fs.readFileSync(path.join(dataRoot,'editorial-demo.json'))).map(a=>a.id).sort());});
test('Creazione e pubblicazione articoli attraverso Next.js',async()=>{let payload={title:'Articolo QA Next',html:'<p>Test locale isolato formattato</p>',channel:'aniem',status:'draft'};let r=await request('/api/admin/articles','POST',payload);assert.equal(r.status,201);created=await r.json();assert.ok(!(await(await request('/api/demo/articles')).json()).some(a=>a.id===created.id));r=await request('/api/admin/articles/'+created.id,'PUT',{...payload,status:'published',version:created.version});assert.equal(r.status,200);assert.ok((await(await request('/api/demo/articles')).json()).some(a=>a.id===created.id));});
test('Contatto e adesione locale registrati e aggiornabili',async()=>{let r=await request('/api/demo/requests','POST',{name:'Verifica Porting',company:'Impresa di test',email:'qa@example.org',interest:'Adesione',message:'Partita IVA: 00000000000',consent:true});assert.equal(r.status,201);const rows=await(await request('/api/demo/requests')).json();assert.equal(rows.length,1);assert.match(rows[0].message,/Adesione/);r=await request('/api/admin/leads/'+rows[0].id,'PATCH',{status:'Gestita',notes:'QA'});assert.equal(r.status,200);assert.equal((await(await request('/api/demo/requests')).json())[0].status,'Gestita');});
test('Origine estranea rifiutata e accesso admin protetto',async()=>{const r=await fetch(base+'/api/demo/articles',{method:'POST',headers:{Origin:'https://example.org','Content-Type':'application/json'},body:'{}'});assert.equal(r.status,403);const admin=await fetch(base+'/admin',{redirect:'manual'});assert.equal(admin.status,302);assert.equal(admin.headers.get('location'),'/admin/login');});
