const crypto=require('crypto');const {z}=require('zod');const sql=require('./db');const {cleanHTML,plain,allowedLocal}=require('./security');
const slugify=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,120)||'articolo';
const schema=z.object({title:z.string().trim().min(3,'Scrivi un titolo di almeno 3 caratteri.').max(220),summary:z.string().max(600).default(''),html:z.string().max(500000).default(''),channel:z.enum(['confapi','aniem','servizi']),status:z.enum(['draft','published','trash']).default('draft'),image:z.string().max(500).default(''),image_alt:z.string().max(250).default(''),services:z.array(z.string()).max(20).default([]),published_at:z.string().nullable().optional(),featured:z.boolean().default(false),version:z.number().int().optional()});
function saveArticle(body,user,id){const input=schema.parse(body);const html=cleanHTML(input.html);if(input.status==='published'&&plain(html).length<10)throw Object.assign(Error('Scrivi il testo dell’articolo prima di pubblicarlo.'),{status:400});if(input.image&&!allowedLocal(input.image))throw Object.assign(Error('Scegli una copertina dalla libreria immagini.'),{status:400});if(input.status==='published'&&input.channel==='servizi'&&!input.services.length)throw Object.assign(Error('Scegli almeno un servizio per questo articolo.'),{status:400});const unique=[...new Set(input.services)];for(const s of unique){if(!sql.get('SELECT id FROM services WHERE id=? AND active=1',s))throw Object.assign(Error('Uno dei servizi selezionati non è più disponibile.'),{status:400});}
return sql.transaction(()=>{const old=id?sql.article(id):null;if(id&&!old)throw Object.assign(Error('Articolo non trovato.'),{status:404});if(old&&input.version!==old.version)throw Object.assign(Error('L’articolo è stato modificato da un’altra sessione. Ricarica la pagina prima di salvare.'),{status:409});const now=new Date().toISOString();let slug=old?.slug||slugify(input.title);if(!old&&sql.get('SELECT id FROM articles WHERE slug=?',slug))slug+='-'+crypto.randomBytes(3).toString('hex');let publishedAt=old?.published_at||null;if(input.published_at){const d=new Date(input.published_at);if(!Number.isFinite(d.getTime())||d.getTime()>Date.now()+60000)throw Object.assign(Error('Inserisci una data valida, non futura. La pubblicazione è immediata.'),{status:400});publishedAt=d.toISOString();}if(input.status==='published'&&!publishedAt)publishedAt=now;
 const a={id:old?.id||crypto.randomUUID(),slug,title:input.title,summary:input.summary.trim()||plain(html).slice(0,200),html,channel:input.channel,status:input.status,image:input.image,image_alt:input.image_alt.trim(),published_at:publishedAt,created_at:old?.created_at||now,updated_at:now,author_id:old?.author_id||user.id,source_url:old?.source_url||null,featured:input.featured?1:0,version:(old?.version||0)+1};
 if(old)sql.run('INSERT INTO revisions(article_id,user_id,data,created_at) VALUES(?,?,?,?)',old.id,user.id,JSON.stringify(old),now);
 if(a.featured&&a.status==='published')sql.run('UPDATE articles SET featured=0 WHERE channel=?',a.channel);
 const keys=Object.keys(a);sql.run(`INSERT INTO articles(${keys.join(',')}) VALUES(${keys.map(()=>'?').join(',')}) ON CONFLICT(id) DO UPDATE SET ${keys.filter(k=>k!=='id').map(k=>k+'=excluded.'+k).join(',')}`,...Object.values(a));
 sql.run('DELETE FROM article_services WHERE article_id=?',a.id);for(const s of unique)sql.run('INSERT INTO article_services(article_id,service_id) VALUES(?,?)',a.id,s);
 sql.run('DELETE FROM revisions WHERE article_id=? AND id NOT IN (SELECT id FROM revisions WHERE article_id=? ORDER BY id DESC LIMIT 30)',a.id,a.id);sql.audit(user.id,'article.'+input.status,a.id);return sql.article(a.id);
});}
function listArticles({channel,service,q='',status='published',page=1,limit=9}={}){const clauses=['a.status=?'],params=[status];if(channel){clauses.push('a.channel=?');params.push(channel);}if(service){clauses.push('EXISTS (SELECT 1 FROM article_services j WHERE j.article_id=a.id AND j.service_id=?)');params.push(service);}if(q){clauses.push("(a.title LIKE ? ESCAPE '\\' OR a.summary LIKE ? ESCAPE '\\')");const like='%'+q.replace(/[\\%_]/g,'\\$&')+'%';params.push(like,like);}const where=clauses.join(' AND ');const total=sql.get('SELECT COUNT(*) AS n FROM articles a WHERE '+where,...params).n;page=Math.min(Math.max(1,Math.floor(Number(page))||1),Math.max(1,Math.ceil(total/limit)));const items=sql.all('SELECT a.* FROM articles a WHERE '+where+' ORDER BY a.featured DESC,COALESCE(a.published_at,a.created_at) DESC LIMIT ? OFFSET ?',...params,limit,(page-1)*limit).map(sql.hydrate);return {items,total,page,pages:Math.max(1,Math.ceil(total/limit))};}
module.exports={saveArticle,listArticles,slugify};
