const crypto=require('crypto');const {promisify}=require('util');const scrypt=promisify(crypto.scrypt);const sanitize=require('sanitize-html');const config=require('./config');const sql=require('./db');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
function equal(a,b){const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&crypto.timingSafeEqual(x,y);}
async function passwordHash(password){const salt=crypto.randomBytes(16).toString('hex');const key=await scrypt(password,salt,64);return salt+':'+key.toString('hex');}
async function passwordVerify(password,stored){const [salt,key]=stored.split(':');return equal((await scrypt(password,salt,64)).toString('hex'),key);}
function cookie(req,name){const raw=(req.headers.cookie||'').split(';').find(c=>c.trim().startsWith(name+'='));try{return raw?decodeURIComponent(raw.trim().slice(name.length+1)):null;}catch{return null;}}
function session(req,res,next){const token=cookie(req,'confapi_v1_membership_session');req.user=null;if(token&&token.length<200){const s=sql.get('SELECT u.id,u.name,u.email,u.role,s.csrf,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=?',hash(token));if(s&&s.expires_at>Date.now()){req.user=s;req.sessionHash=hash(token);}}next();}
function requireUser(req,res,next){if(req.user)return next();if(req.originalUrl.startsWith('/api/'))return res.status(401).json({error:'Accedi di nuovo per continuare.'});return res.redirect('/admin/login');}
function requireAdmin(req,res,next){return req.user?.role==='admin'?next():res.status(403).json({error:'Questa operazione richiede un amministratore.'});}
function csrf(req,res,next){if(['GET','HEAD','OPTIONS'].includes(req.method))return next();if(!equal(req.headers['x-csrf-token']||req.body?._csrf,req.user?.csrf))return res.status(403).json({error:'Sessione scaduta. Ricarica la pagina prima di salvare.'});next();}
function origin(req,res,next){if(['GET','HEAD','OPTIONS'].includes(req.method))return next();const o=req.get('origin');const host=req.get('host');const allowed=[config.appURL,`http://${host}`,`https://${host}`].filter(Boolean);if(o&&!allowed.includes(o))return res.status(403).json({error:'Origine della richiesta non consentita.'});if(req.get('sec-fetch-site')==='cross-site')return res.status(403).json({error:'Richiesta non consentita.'});next();}
function createSession(user,res){const token=crypto.randomBytes(32).toString('hex');const csrf=crypto.randomBytes(32).toString('hex');sql.run('DELETE FROM sessions WHERE expires_at<?',Date.now());sql.run('INSERT INTO sessions(token_hash,user_id,csrf,expires_at) VALUES(?,?,?,?)',hash(token),user.id,csrf,Date.now()+8*60*60*1000);res.cookie('confapi_v1_membership_session',token,{httpOnly:true,secure:config.production,sameSite:'lax',maxAge:8*60*60*1000,path:'/'});}
const allowedLocal=u=>typeof u==='string'&&/^\/(uploads|assets)\/[a-zA-Z0-9_./% -]+$/.test(u)&&!u.includes('..');
function cleanHTML(html){return sanitize(html||'',{allowedTags:['p','br','strong','b','em','i','u','s','h2','h3','h4','ul','ol','li','blockquote','a','img','figure','figcaption','hr','table','thead','tbody','tr','td','th','span','sub','sup'],allowedAttributes:{a:['href','title','target','rel'],img:['src','alt','width','height'],ol:['start'],li:['data-list'],span:['class'],p:['class'],h2:['class'],h3:['class'],td:['colspan','rowspan'],th:['colspan','rowspan']},allowedClasses:{'*':['ql-align-center','ql-align-right','ql-align-justify','ql-indent-1','ql-indent-2']},allowedSchemes:['http','https','mailto','tel'],allowProtocolRelative:false,transformTags:{a:(tag,attrs)=>({tagName:'a',attribs:{...attrs,rel:'noopener noreferrer',...(attrs.href?.startsWith('http')?{target:'_blank'}:{})}})},exclusiveFilter:frame=>frame.tag==='img'&&!allowedLocal(frame.attribs.src),disallowedTagsMode:'discard'});}
function plain(html){return sanitize(html,{allowedTags:[],allowedAttributes:{}}).replace(/&nbsp;/g,' ').trim();}
module.exports={hash,equal,passwordHash,passwordVerify,cookie,session,requireUser,requireAdmin,csrf,origin,createSession,cleanHTML,plain,allowedLocal};
