const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(n='arrow')=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${{arrow:'M4 12h16m-6-6 6 6-6 6',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',file:'M4 2h11l5 5v15H4zM14 2v6h6M8 12h8M8 16h8',image:'M3 3h18v18H3zM3 17l6-6 4 4 3-3 5 5M9 7h.01',plus:'M12 4v16M4 12h16',mail:'M2 4h20v16H2zM2 5l10 8L22 5',menu:'M3 6h18M3 12h18M3 18h18'}[n]||'M4 12h16m-6-6 6 6-6 6'}"/></svg>`;
const labels={confapi:'News CONFAPI',aniem:'News ANIEM',servizi:'Servizi alle imprese'};
const date=d=>d?new Date(d).toLocaleDateString('it-IT',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Rome'}):'Archivio';
function field(name,label,{type='text',required=false,value='',max=150,autocomplete='off'}={}){return `<label class="field" for="${name}">${label}${required?' <span aria-label="obbligatorio">*</span>':''}<input id="${name}" name="${name}" type="${type}" ${required?'required':''} value="${esc(value)}" maxlength="${max}" autocomplete="${autocomplete}"></label>`;}

function layout(title,body,{scripts=[],csrf=''}={}){return `<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${esc(title)} | CONFAPI Roma</title>${csrf?`<meta name="csrf-token" content="${esc(csrf)}">`:''}<link rel="icon" href="/assets/logos/favicon.ico"><link rel="stylesheet" href="/cms-assets/base.css"><link rel="stylesheet" href="/cms-assets/site.css"><link rel="stylesheet" href="/cms-assets/vendor/quill.snow.css"><script src="/cms-assets/site.js" defer></script>${scripts.map(s=>`<script src="${s}" defer></script>`).join('')}</head><body class="admin-body"><a class="skip" href="#main">Vai al contenuto</a>${body}<div id="toast" role="status" aria-live="polite"></div></body></html>`;}
function article(a){return `<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${esc(a.title)} · Anteprima V1</title><link rel="stylesheet" href="/css/magazine.css"></head><body><main class="wrap" id="main"><p class="notice">Anteprima redazionale · V1</p><article><div class="article-head"><span class="tag">${esc(labels[a.channel])}</span><h1>${esc(a.title)}</h1><p class="standfirst">${esc(a.summary)}</p><div class="meta">${date(a.published_at)}</div></div>${a.image?`<img class="article-image" src="${esc(a.image)}" alt="${esc(a.image_alt)}">`:''}<div class="article-body">${a.html}</div></article></main></body></html>`;}
function notFound(){return layout('Non trovato','<main id="main" class="wrap"><h1>Contenuto non trovato</h1><a href="/admin">Torna alla redazione</a></main>');}
function error(message){return layout('Operazione non riuscita',`<main id="main" class="wrap"><h1>Operazione non riuscita</h1><p>${esc(message)}</p><a href="/admin">Torna alla redazione</a></main>`);}
module.exports={esc,icon,labels,date,layout,field,article,notFound,error};
