const fs=require('fs');const path=require('path');const {PDFDocument,StandardFonts,rgb}=require('pdf-lib');const sharp=require('sharp');const {z}=require('zod');const config=require('./config');
const sectors=['agricoltura','commercio','turismo','cooperazione','industria','artigianato','servizi','altro'];
const industries=['alimentari','chimico','edilizia','grafici editoria','informatica','legno arredamento','meccanico','servizi','trasporti','immobiliaristi','sanità','altro'];
const fieldDefinitions=[
 ['company','Ragione sociale',80,122,474,130],['legal_city','Comune della sede legale',113,140,111,60],['legal_province','Provincia',235,140,17,2],['legal_street','Via / piazza',274,140,146,85],['legal_number','Numero civico',436,140,20,8],['legal_zip','CAP',479,140,76,5],
 ['office_city','Comune della sede operativa',127,158,116,60],['office_province','Provincia',245,158,17,2],['office_street','Via / piazza',280,158,143,85],['office_number','Numero civico',439,158,23,8],['office_zip','CAP',485,158,69,5],
 ['tax_code','Codice fiscale aziendale',95,177,170,16],['vat','Partita IVA',318,177,237,11],['phone','Telefono',51,195,70,22],['fax','Fax',142,195,69,22],['email','Email',242,195,131,100],['pec','PEC',399,195,156,100],
 ['representative','Nome e cognome del legale rappresentante',234,213,320,100],['birth_city','Comune di nascita',75,232,177,60],['birth_province','Provincia di nascita',261,232,17,2],['birth_date','Data di nascita',295,232,260,10],['residence_city','Comune di residenza',87,250,152,60],['residence_province','Provincia',248,250,17,2],['residence_street','Indirizzo di residenza',287,250,172,85],['residence_number','Numero civico',476,250,80,8],
 ['consultant','Consulente del lavoro / commercialista',196,268,148,80],['consultant_phone','Telefono del consulente',358,268,62,22],['consultant_email','Email del consulente',442,268,112,100],
 ['employees','Addetti complessivi',359,397,52,6],['managers','Dirigenti',83,420,38,6],['supervisors','Quadri',178,420,38,6],['clerks','Impiegati',266,420,33,6],['workers','Operai',361,420,42,6],['fee','Quota associativa annua concordata (€)',327,584,48,10],['place','Luogo',37,620,64,50],['date','Data',113,620,83,10]
];
const fieldsSchema=z.object(Object.fromEntries(fieldDefinitions.map(([key,label,x,y,w,max])=>[key,z.string().trim().max(max,`${label}: massimo ${max} caratteri.`).default('')])));
const signature=z.string().max(1500000).regex(/^data:image\/png;base64,[A-Za-z0-9+/=]+$/,'Inserisci una firma valida.').optional().or(z.literal(''));
const membershipSchema=z.object({fields:fieldsSchema,sectors:z.array(z.enum(sectors)).max(8).default([]),industries:z.array(z.enum(industries)).max(12).default([]),signature,privacySignature:signature,declarations:z.boolean().default(false),privacy:z.boolean().default(false),website:z.string().max(200).default('')});
function validateMembership(body,final=false){const value=membershipSchema.parse(body);const f=value.fields;for(const k of ['email','pec','consultant_email'])if(f[k]&&!z.email().safeParse(f[k]).success)throw Object.assign(Error('Controlla il campo '+fieldDefinitions.find(x=>x[0]===k)[1]+'.'),{status:400});if(f.vat&&!/^\d{11}$/.test(f.vat))throw Object.assign(Error('La partita IVA deve contenere 11 cifre.'),{status:400});for(const k of ['legal_zip','office_zip'])if(f[k]&&!/^\d{5}$/.test(f[k]))throw Object.assign(Error('Il CAP deve contenere 5 cifre.'),{status:400});for(const k of ['employees','managers','supervisors','clerks','workers'])if(f[k]&&!/^\d{1,6}$/.test(f[k]))throw Object.assign(Error('Il numero di addetti deve essere un intero positivo o zero.'),{status:400});const sum=['managers','supervisors','clerks','workers'].reduce((n,k)=>n+Number(f[k]||0),0);if(f.employees&&sum!==Number(f.employees))throw Object.assign(Error('La somma di dirigenti, quadri, impiegati e operai deve coincidere con il totale addetti.'),{status:400});for(const k of ['date','birth_date'])if(f[k]&&(!/^\d{4}-\d{2}-\d{2}$/.test(f[k])||!Number.isFinite(Date.parse(f[k]))||new Date(f[k]).toISOString().slice(0,10)!==f[k]||Date.parse(f[k])>Date.now()))throw Object.assign(Error('Controlla le date inserite: devono essere valide e non future.'),{status:400});
if(final){for(const k of ['company','legal_city','legal_province','legal_street','legal_number','legal_zip','tax_code','vat','email','representative','birth_city','birth_date','residence_city','residence_street','employees','place','date'])if(!f[k])throw Object.assign(Error('Completa il campo: '+fieldDefinitions.find(x=>x[0]===k)[1]+'.'),{status:400});if(!value.sectors.length||!value.industries.length)throw Object.assign(Error('Scegli settore e attività prevalente.'),{status:400});if(!value.signature||!value.privacySignature||!value.declarations||!value.privacy)throw Object.assign(Error('Conferma le dichiarazioni e inserisci entrambe le firme.'),{status:400});if(!f.fee)throw Object.assign(Error('Concorda la quota con la segreteria e inseriscila prima di inviare la domanda. Puoi intanto scaricare la bozza.'),{status:400});}if(f.fee&&!/^\d{1,7}([.,]\d{1,2})?$/.test(f.fee))throw Object.assign(Error('Inserisci una quota valida.'),{status:400});return value;}
async function signatureBytes(data){if(!data)return null;const bytes=Buffer.from(data.split(',')[1],'base64');if(bytes.length>1024*1024)throw Object.assign(Error('La firma è troppo grande.'),{status:400});const image=sharp(bytes,{limitInputPixels:4000000});const meta=await image.metadata();if(meta.format!=='png')throw Object.assign(Error('La firma deve essere un’immagine PNG.'),{status:400});const stats=await image.stats();if(stats.channels.every(c=>c.stdev<.2))throw Object.assign(Error('La firma è vuota. Disegnala nello spazio indicato.'),{status:400});return image.trim({threshold:10}).resize({width:700,height:160,fit:'inside',withoutEnlargement:true}).png().toBuffer();}
const fieldLines=require('./pdf-field-lines');
function clearFieldLine(page,height,name){const b=fieldLines[name];page.drawRectangle({x:b.left,y:height-b.bottom-.35,width:b.right-b.left,height:b.bottom-b.top+.7,color:rgb(1,1,1)});page.drawRectangle({x:b.left-.8,y:height-b.bottom-.5,width:b.right-b.left+1.6,height:2.8,color:rgb(1,1,1)});}
const printable=s=>String(s).replace(/[\u2018\u2019]/g,"'").replace(/[\u201c\u201d]/g,'"').replace(/[^\x20-\x7e\xa0-\xff]/g,'?');
async function createMembershipPDF(value,{draft=true}={}){const bytes=fs.readFileSync(path.join(config.root,'public/assets/docs/scheda-adesione-originale.pdf'));const pdf=await PDFDocument.load(bytes);const page=pdf.getPage(0);const font=await pdf.embedFont(StandardFonts.Helvetica);const height=page.getHeight();for(const [name,label,x,top,width]of fieldDefinitions){let text=value.fields[name]||'';if(name==='date'||name==='birth_date')text=text?text.split('-').reverse().join('/'):'';if(!text)continue;text=printable(text);let size=9;while(font.widthOfTextAtSize(text,size)>width-2&&size>5.5)size-=.2;if(font.widthOfTextAtSize(text,size)>width-2)throw Object.assign(Error(`Il campo ${label} è troppo lungo per lo spazio sul PDF. Abbrevia il valore.`),{status:400});clearFieldLine(page,height,name);page.drawText(text,{x,y:height-top-8.5,size,font,color:rgb(.06,.16,.28)});}
 const coordinates=[[57,457],[171,457],[305,457],[426,457],[57,469],[171,469],[305,469],[426,469]];value.sectors.forEach(s=>{const [x,t]=coordinates[sectors.indexOf(s)];page.drawText('X',{x:x+1,y:height-t-8,size:9,font});});
 value.industries.forEach(s=>{const i=industries.indexOf(s),x=[57,171,305,426][i%4],t=[506,518,530][Math.floor(i/4)];page.drawText('X',{x:x+1,y:height-t-8,size:9,font});});
 for(const [key,top]of [['signature',633],['privacySignature',784]]){const image=await signatureBytes(value[key]);if(image){clearFieldLine(page,height,key);const embedded=await pdf.embedPng(image);const dim=embedded.scaleToFit(137,18);page.drawImage(embedded,{x:353,y:height-top-dim.height,width:dim.width,height:dim.height});}}
 for(const [name,x,width]of [['place',37,64],['date',113,83]]){let text=value.fields[name]||'';if(name==='date')text=text?text.split('-').reverse().join('/'):'';text=printable(text);if(text){let size=9;while(font.widthOfTextAtSize(text,size)>width&&size>5.5)size-=.2;clearFieldLine(page,height,name==='place'?'privacyPlace':'privacyDate');page.drawText(text,{x,y:height-780.5,size,font});}}
 pdf.setTitle('Domanda di adesione CONFAPI Roma'+(draft?' - Bozza':''));pdf.setSubject('Compilazione del modulo originale e firme grafiche');pdf.setProducer('CONFAPI Roma - Portale associativo');if(draft)page.drawText('BOZZA - da verificare prima dell’invio'.replace('’',"'"),{x:36,y:153,size:8,font,color:rgb(.4,.4,.4)});return Buffer.from(await pdf.save());}
module.exports={fieldDefinitions,sectors,industries,validateMembership,createMembershipPDF};
